name: convertimg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          ref: main
      #     - name: Cache
      #       uses: actions/cache@v2.1.6
      #       with:
      #         # A list of files, directories, and wildcard patterns to cache and restore
      #         path: |
      #               'node_modules'
      #         # An explicit key for restoring and saving the cache
      #         key: ${{ runner.os }}-cache-1
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v1.1.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      #     - name: Optimize Images
      #       uses: 9sako6/imgcmp@1.0.0
      - run: yarn img
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
