name: convertimg

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: main
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
              'node_modules'
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-cache-1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#     - name: Optimize Images
#       uses: 9sako6/imgcmp@1.0.0
    - run: npm img
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'pages'
        commit-message: 'Push OptimizedOptimize'
        force-add: 'true'
        files: '*'
        name: Image Bot
        email: imagebot@example.com

