name: Squash Main
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          ref: main
      - name: Configure Git Credentials
        run: |
          git config --local user.email "94558721+YieldingBot@users.noreply.github.com"
          git config --local user.name "YieldingBot[BOT]"
      - name: Soft Reset
        run: |
          COMMIT_COUNT=$(git log --pretty=oneline --since="1 days" | wc -l) 
          echo "Resetting to HEAD~$COMMIT_COUNT"
          git reset --soft HEAD~$COMMIT_COUNT 
      - name: Add Files
        run: |
          git add --all .
      - name: Commit
        run: |
          git commit -am "Squashed changes for $(date +%F) ($COMMIT_COUNT commits, including other squashes today)" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: master
          force: true
